version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - mail
    volumes:
      - '.:/app'
    env_file:
      - .env
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      MAIL_HOST: 'mail'
      MAIL_PORT: 25
      MAIL_ENCRYPTION: 'false'
      MYSQL_ADDON_DB: sevanova
      MYSQL_ADDON_HOST: db
      MYSQL_ADDON_PASSWORD: sevanova
      MYSQL_ADDON_PORT: 3306
      MYSQL_ADDON_USER: sevanova
    networks:
      - traefik
    labels:
      traefik.port: '80'
      traefik.backend: '${URL}'
      traefik.docker.network: 'traefikforwebdev_webgateway'
      traefik.frontend.entryPoints: 'http'
      traefik.frontend.rule: 'Host:${URL}'

  db:
    image: mariadb:10.4.12
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'database:/var/lib/mysql'
    networks:
      - traefik
    environment:
      MYSQL_DATABASE: sevanova
      MYSQL_USER: sevanova
      MYSQL_PASSWORD: sevanova
      MYSQL_ROOT_PASSWORD: sevanova
    labels:
      traefik.enable: false

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - traefik
    labels:
      traefik.backend: 'pma.${URL}'
      traefik.docker.network: 'traefikforwebdev_webgateway'
      traefik.frontend.entryPoints: 'http'
      traefik.frontend.rule: 'Host:pma.${URL}'

  mail:
    image: djfarrelly/maildev
    networks:
      - traefik
    labels:
      traefik.backend: 'mail.${URL}'
      traefik.docker.network: 'traefikforwebdev_webgateway'
      traefik.enable: 'true'
      traefik.frontend.entryPoints: 'http'
      traefik.frontend.rule: 'Host:mail.${URL}'
      traefik.port: '80'

networks:
  traefik:
    external:
      name: traefikforwebdev_webgateway

volumes:
  database:
